# Generated by Django 5.2.11 on 2026-02-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='locations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
